### PR TITLE
Conditional tracking

### PR DESCRIPTION
**Pull request by piotrekbator**
A small change to disable tracking when no pixel ID was provided.

### CODE REVIEW

**Comment by jasonkriss** [comment]
Thanks for the PR @piotrekbator! I wonder if maybe it'd make more sense to maybe just raise an error if pixel id isn't provided? I would say if someone isn't gonna provide an id, then they should just remove the addon. What do you think?

**Comment by piotrekbator** [comment]
What I wanted to achieve was to be able to only enable the pixel in specific environments. So that it wouldn't track me in development mode (unless I provide an ID to test the pixel) and still work in production.

Do you have a better idea to solve that?

**Comment by jasonkriss** [comment]
ahh gotcha. Thanks for explaining! Great idea! I think that's a very valid use case. I think we should maybe be a lil more explicit about it though... maybe have a disabled flag that you can set in the config. Have it default to false, but if someone sets `disabled: true` then it doesn't track. What do you think?

**Comment by piotrekbator** [comment]
Having a "disabled" flag would mean - in most cases - that you'd need to set it in dev, test and staging environments. That wouldn't be nice, would it?

The biggest problem I see with my solution is that people might be confused on why the pixel is not working when they set the config option in just one environment. So maybe writing a message to the console saying something like "FB Pixel is not enabled. To enable it set facebook-pixel-id.id in config".
How does it sound?

BTW I think that the dasherized name of the config option is not matching convention - all the other config options are in lower camel case. Would you consider changing it?

**Comment by jasonkriss** [comment]
Generally speaking, I prefer to keep configuration explicit. However in this case, I think you bring up a good point. There is really no reason to track outside of production except in rare cases. So we want to make that use case as easy as possible. 

So I'm on board with the PR. Thanks! Do you mind adding something to the Readme to make this more explicit?

As far as the dasherized vs camel case, I'm definitely open to changing it. I always hate having to quote the dasherized names anyway. I think the dasherized names used to be more of a convention. That's the only reason I was doing it.

**Comment by piotrekbator** [comment]
I've updated the Readme, hope it's OK.

I've justo noticed that we've already exchanged a series of emails about pagefront a few weeks ago! Nice to meet you again :)

**Comment by jasonkriss** [comment]
Thought your name looked familiar :). Likewise! Readme looks great! One last request (sorry) do you mind just squashing your commits? I'll get it merged in and released right away

**Comment by piotrekbator** [comment]
Commits squashed.

Will you switch from dasherized to camelized config option name or should I make a separate PR?

**Comment by jasonkriss** [comment]
Thanks @piotrekbator! If you don't mind putting together the PR, that'd be greatly appreciated.

**Pull request merged**
